//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift MMIO open source project
//
// Copyright (c) 2023 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
//
//===----------------------------------------------------------------------===//

import Testing

@testable import SVD
@testable import SVD2Swift

extension SVD2SwiftTests {
  private static let testInterruptsDevice = SVDDevice(
    name: "ExampleDevice",
    description: "An example device",
    addressUnitBits: 8,
    width: 32,
    registerProperties: .init(
      size: 32,
      access: .readWrite),
    peripherals: .init(
      peripheral: [
        .init(
          name: "TIMER0",
          description: "Timer 0",
          baseAddress: 0x1000,
          interrupt: [
            .init(name: "TIMER0", description: "Timer 0", value: 4),
            .init(name: "TIMER0_CC", value: 5),
            .init(name: "TIMER0_EXTI", description: "Timer 0, via EXTI", value: 4),
          ]),
        .init(
          derivedFrom: "TIMER0",
          name: "TIMER1",
          description: "Timer 1",
          baseAddress: 0x2000),
        .init(
          name: "WDT",
          description: "Watchdog",
          baseAddress: 0x3000,
          interrupt: [
            .init(name: "WDT", description: "Watchdog   timer", value: 0)
          ]),
      ]))

  @Test func interrupts() throws {
    assertSVD2SwiftOutput(
      svdDevice: Self.testInterruptsDevice,
      expected: [
        "Device.swift": """
        // Generated by svd2swift.

        import MMIO

        /// Timer 0
        let timer0 = TIMER0(unsafeAddress: 0x1000)

        /// Timer 1
        let timer1 = TIMER1(unsafeAddress: 0x2000)

        /// Watchdog
        let wdt = WDT(unsafeAddress: 0x3000)

        /// Device interrupts, by NVIC number.
        enum Interrupt: UInt16 {
          /// Watchdog timer
          case wdt = 0

          /// Timer 0
          case timer0 = 4

          /// Timer 0, via EXTI
          static var timer0_exti: Self { .timer0 }

          /// TIMER0_CC
          case timer0_cc = 5
        }

        """,

        "TIMER0.swift": """
        // Generated by svd2swift.

        import MMIO

        /// Timer 0
        @RegisterBlock
        struct TIMER0 {
        }

        """,

        "TIMER1.swift": """
        // Generated by svd2swift.

        import MMIO

        /// Timer 1
        typealias TIMER1 = TIMER0


        """,

        "WDT.swift": """
        // Generated by svd2swift.

        import MMIO

        /// Watchdog
        @RegisterBlock
        struct WDT {
        }

        """,
      ])
  }
}
