//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift MMIO open source project
//
// Copyright (c) 2023 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
//
//===----------------------------------------------------------------------===//

import Testing

@testable import SVD
@testable import SVD2Swift

extension SVD2SwiftTests {
  /// A register wider than the device default, and one deriving from it
  /// without restating its size.
  private static let testDerivedRegisterPropertiesDevice = SVDDevice(
    name: "ExampleDevice",
    description: "An example device",
    addressUnitBits: 8,
    width: 32,
    registerProperties: .init(
      size: 32,
      access: .readWrite),
    peripherals: .init(
      peripheral: [
        .init(
          name: "ExamplePeripheral",
          description: "An example peripheral",
          baseAddress: 0x1000,
          registers: .init(
            cluster: [],
            register: [
              .init(
                name: "Wide",
                description: "A 64 bit register",
                addressOffset: 0x0,
                registerProperties: .init(size: 64),
                fields: .init(
                  field: [
                    .init(
                      name: "A",
                      bitRange: .offsetWidth(
                        .init(bitOffset: 0, bitWidth: 40)))
                  ])),
              .init(
                derivedFrom: "Wide",
                name: "DerivedWide",
                description: "Derives its size and fields from Wide",
                addressOffset: 0x8),
            ]))
      ]))

  /// A derived register inherits the register properties of its parent, not the
  /// device default.
  @Test func derived_register_inheritsRegisterProperties() throws {
    assertSVD2SwiftOutput(
      svdDevice: Self.testDerivedRegisterPropertiesDevice,
      expected: [
        "Device.swift": """
        // Generated by svd2swift.

        import MMIO

        /// An example peripheral
        let exampleperipheral = ExamplePeripheral(unsafeAddress: 0x1000)

        """,

        "ExamplePeripheral.swift": """
        // Generated by svd2swift.

        import MMIO

        /// An example peripheral
        @RegisterBlock
        struct ExamplePeripheral {
          /// A 64 bit register
          @RegisterBlock(offset: 0x0)
          var wide: Register<Wide>

          /// Derives its size and fields from Wide
          @RegisterBlock(offset: 0x8)
          var derivedwide: Register<DerivedWide>
        }

        extension ExamplePeripheral {
          /// A 64 bit register
          @Register(bitWidth: 64)
          struct Wide {
            /// A
            @ReadWrite(bits: 0..<40)
            var a: A
          }

          /// Derives its size and fields from Wide
          @Register(bitWidth: 64)
          struct DerivedWide {
            /// A
            @ReadWrite(bits: 0..<40)
            var a: A
          }
        }

        """,
      ])
  }
}
