version: 1
builder:
  configs:
    - documentation_targets:
        - MMIO
        - SVD
        - SVD2LLDB
        - SVD2Swift
      custom_documentation_parameters:
        - --enable-experimental-overloaded-symbol-presentation
        - --symbol-graph-minimum-access-level
        - public
