version: 1
builder:
  configs:
    - documentation_targets:
      - MMIO
      - SVD
      - SVD2LLDB
      - SVD2Swift
      custom_documentation_parameters:
      - --symbol-graph-minimum-access-level
      - public
      swift_version: 6.0
