//===-- LLDB.h --------------------------------------------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef LLDB_API_LLDB_H
#define LLDB_API_LLDB_H

#include "SBAddress.h"
#include "SBAttachInfo.h"
#include "SBBlock.h"
#include "SBBreakpoint.h"
#include "SBBreakpointLocation.h"
#include "SBBreakpointName.h"
#include "SBBroadcaster.h"
#include "SBCommandInterpreter.h"
#include "SBCommandInterpreterRunOptions.h"
#include "SBCommandReturnObject.h"
#include "SBCommunication.h"
#include "SBCompileUnit.h"
#include "SBData.h"
#include "SBDebugger.h"
#include "SBDeclaration.h"
#include "SBDefines.h"
#include "SBEnvironment.h"
#include "SBError.h"
#include "SBEvent.h"
#include "SBExecutionContext.h"
#include "SBExpressionOptions.h"
#include "SBFile.h"
#include "SBFileSpec.h"
#include "SBFileSpecList.h"
#include "SBFormat.h"
#include "SBFrame.h"
#include "SBFunction.h"
#include "SBHostOS.h"
#include "SBInstruction.h"
#include "SBInstructionList.h"
#include "SBLanguageRuntime.h"
#include "SBLaunchInfo.h"
#include "SBLineEntry.h"
#include "SBListener.h"
#include "SBMemoryRegionInfo.h"
#include "SBMemoryRegionInfoList.h"
#include "SBModule.h"
#include "SBModuleSpec.h"
#include "SBPlatform.h"
#include "SBProcess.h"
#include "SBProcessInfo.h"
#include "SBQueue.h"
#include "SBQueueItem.h"
#include "SBReproducer.h"
#include "SBSection.h"
#include "SBSourceManager.h"
#include "SBStream.h"
#include "SBStringList.h"
#include "SBStructuredData.h"
#include "SBSymbol.h"
#include "SBSymbolContext.h"
#include "SBSymbolContextList.h"
#include "SBTarget.h"
#include "SBThread.h"
#include "SBThreadCollection.h"
#include "SBThreadPlan.h"
#include "SBTrace.h"
#include "SBType.h"
#include "SBTypeCategory.h"
#include "SBTypeEnumMember.h"
#include "SBTypeFilter.h"
#include "SBTypeFormat.h"
#include "SBTypeNameSpecifier.h"
#include "SBTypeSummary.h"
#include "SBTypeSynthetic.h"
#include "SBUnixSignals.h"
#include "SBValue.h"
#include "SBValueList.h"
#include "SBVariablesOptions.h"
#include "SBWatchpoint.h"

#include "_SBSwift.h"

#endif // LLDB_API_LLDB_H
