version: "3"

services:

  runtime-setup:
    image: swift-mmio:22.04-main
    build:
      args:
        namespace: "swiftlang/swift"
        ubuntu_version: "jammy"
        swift_version: "nightly"

  soundness:
    image: swift-mmio:22.04-main

  test:
    image: swift-mmio:22.04-main

  shell:
    image: swift-mmio:22.04-main
