# this file is not designed to be run directly
# instead, use the docker-compose.<os>.<swift> files
# eg docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.2204.59.yaml run test
version: "3"

services:

  runtime-setup:
    image: swift-mmio:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: swift-mmio:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code:z
    working_dir: /code

  soundness:
    <<: *common
    command: /bin/bash -xcl "swift -version && uname -a && make lint"

  test:
    <<: *common
    command: /bin/bash -xcl "make test CONFIGURATION=release"

  shell:
    <<: *common
    entrypoint: /bin/bash
