version: "3"

services:

  runtime-setup:
    image: swift-mmio:22.04-5.10
    build:
      args:
        namespace: "swift"
        ubuntu_version: "jammy"
        swift_version: "5.10"

  soundness:
    image: swift-mmio:22.04-5.10
    command: /bin/bash -xcl "swift -version && uname -a"

  test:
    image: swift-mmio:22.04-5.10
    command: /bin/bash -xcl "make test CONFIGURATION=release SKIP_LINT=1"

  shell:
    image: swift-mmio:22.04-5.10
