name: Apple CC Matrix

permissions:
  contents: read

on:
  workflow_call:

jobs:
  apple-cc-build:
    name: ${{ matrix.os.name }} (Xcode ${{ matrix.xcode_version }} - ${{ matrix.macos_version }} - ${{ matrix.macos_arch }})
    runs-on: [self-hosted, macos, "${{ matrix.macos_version }}", "${{ matrix.macos_arch }}"]
    strategy:
      fail-fast: false
      matrix:
        xcode_version: ["26.4"]
        os:
          - name: iOS
            platform: iOS
          - name: tvOS
            platform: tvOS
          - name: visionOS
            platform: xrOS
          - name: watchOS
            platform: watchOS
        macos_version: [tahoe]
        macos_arch: [ARM64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install xcbeautify
        run: |
          curl -L https://github.com/cpisciotta/xcbeautify/releases/download/3.2.1/xcbeautify-3.2.1-arm64-apple-macosx.zip -o xcbeautify.zip
          sha256 -c ed32972e41bc3aa19588f8b0f4a0209ef70c663ad60bbf4ad84a2de73355d637 xcbeautify.zip
          unzip xcbeautify.zip -d /tmp
          chmod +x /tmp/xcbeautify
          /tmp/xcbeautify --version
      - name: Select Xcode
        run: echo "DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode_version }}.app" >> $GITHUB_ENV
      - name: Swift version
        run: xcrun swift --version
      - name: Build / Test
        run: xcodebuild build -scheme swift-mmio-Package -destination generic/platform=${{ matrix.os.platform }} | /tmp/xcbeautify
        timeout-minutes: 60
